### ISSUE TITLE
❓ Im getting the error: package com.mrousavy.camera does not exist

### ISSUE THREAD

**Issue by alphonse92** [cuvent/react-native-vision-camera#1039]
### Question

Im getting the error: package com.mrousavy.camera does not exist

<img width="930" alt="Screen Shot 2022-05-11 at 5 11 49 PM" src="https://user-images.githubusercontent.com/18203585/167956024-af7306af-2d32-475c-809e-9a2249a1c706.png">

### What I tried

Cleaned modules and Following the examples, the guide and other resources

### VisionCamera Version

2.13.3

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by zhaleTaheri** [comment]
I have the same problem

**Comment by mauro-rogledi** [comment]
I don't using Expo but I've same problem

**Comment by alphonse92** [comment]
I don't know how I solved this, but maybe it can be helpful for yall. After getting this error I opened the project with Android studio. Android Studio started to clean the project and then, I ran `cd android && ./gradlew clean` after that, I was able to run the project.

On the other hand, I removed all manual linkings I made

**Comment by alphonse92** [comment]
I'll keep this open because there isn't information about the process of building this library when we run the Project. Or maybe it happen randomly

**Comment by biskis** [comment]
And updates here? I have the same error now after cleaning.

**Comment by zhaleTaheri** [comment]
My problem was solved
for android
- rm -rf yarn.lock package-lock.json node_modules ios/Pods ios/Podfile.lock android/app/build
- yarn && cd ios && pod update && cd ..
- npx pod-install
- yarn cache clean
- yarn clean:android
- yarn android
for ios
- rm -rf yarn.lock package-lock.json node_modules ios/Pods ios/Podfile.lock android/app/build
- yarn && cd ios && pod update && cd ..
- npx pod-install
- yarn cache clean
- yarn ios

**Comment by pistonsky** [comment]
For those who are on Mac.

The issue may appear when you have followed a wrong version of “Getting started” doc during your Mac setup for React Native development. You need to follow the correct one, depending on the version of react native that your project is using.

In my case, I needed to uninstall java, and install it again, but using AdoptOpenJDK, instead of Zulu:
```
brew uninstall --cask zulu11
brew install --cask adoptopenjdk/openjdk/adoptopenjdk11
```
I actually even tried to install java 17, so I had to uninstall both `zulu11` and `zulu17`.

**Comment by jbrodriguez** [comment]
i was having this same problem, no amount of cleaning fixed, except applying this patch to the v2.40.0 of the package https://github.com/mrousavy/react-native-vision-camera/pull/1116/files

**Comment by jasbirrajrana** [comment]
any fix for this i m getting the exact same issue?

**Comment by jasbirrajrana** [comment]
@mrousavy

**Comment by danielmark0116** [comment]
> For those who are on Mac.
> 
> The issue may appear when you have followed a wrong version of “Getting started” doc during your Mac setup for React Native development. You need to follow the correct one, depending on the version of react native that your project is using.
> 
> In my case, I needed to uninstall java, and install it again, but using AdoptOpenJDK, instead of Zulu:
> 
> ```
> brew uninstall --cask zulu11
> brew install --cask adoptopenjdk/openjdk/adoptopenjdk11
> ```
> 
> I actually even tried to install java 17, so I had to uninstall both `zulu11` and `zulu17`.

I can confirm that it solved it on my setup as well!

I had zulu's 11 version. I got rid of this one and installed the adoptopen one (used jenv to swithc between versions). Everything works now.

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

**Comment by DanielWoldehana** [comment]
@mrousavy @pistonsky I am on react-native 0.73.1 which requires java 17 currently I am using zulu 17 and still getting the same error caused by vision-camera-code-scanner, are there any solutions for this?

**Comment by IgorDePaula** [comment]
He created this error on purpose to monetize his component. This component is no longer open source. Consider using another module.
