### ISSUE TITLE
🐛 Possible frame processor memory leak on iOS

### ISSUE THREAD

**Issue by astanb** [cuvent/react-native-vision-camera#1098]
### What were you trying to do?

Been investigating memory issues on my app, created a stripped down repo to try and find the culprit through trial and error.

I observed running an empty frame processor on iOS slowly increases memory without it being released.

This effect is multiplied if the frame processor does work using a frame processor plugin and/or calls over to react.

I created a repo here https://github.com/alexstanbury/RNVC-Leak

### What happened instead?

Memory increased over time without being released.

![Screenshot 2022-06-17 at 16 24 00](https://user-images.githubusercontent.com/809537/174339646-a9a8a291-5c27-41ed-b7c0-f9b9477d2061.png)
![Screenshot 2022-06-17 at 16 25 58](https://user-images.githubusercontent.com/809537/174339651-dedcb80e-07be-4926-8e13-59fa428ec8ed.png)

### How to reproduce?

```tsx

yarn && cd ios && pod install && cd ..
```

Open app, let it settle for a few seconds, observe memory usage, toggle camera and leave it to run for a while, observe memory increase. Toggle camera again, observe memory baseline gradually increases after each toggle on/off.

### Device

iPhone XR

### VisionCamera Version

2.13.3

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Huh, interesting! I assume this should be reproduceable in the example app here as well?

Do you notice something similar on Android?

**Comment by astanb** [comment]
I've done a bit more digging and testing. I don't see any issues on Android, memory gets used but then cleared by the GC as expected

With my repo on iOS in release mode, these are the kind of mallocs that are building up:

![Screenshot 2022-06-21 at 10 44 09](https://user-images.githubusercontent.com/809537/174770428-cc0fddda-a404-4c38-bb6d-6bd76850c210.png)
![Screenshot 2022-06-21 at 10 44 15](https://user-images.githubusercontent.com/809537/174770439-8a15a2dc-d837-48fa-a882-7b07e523bb62.png)

I tried with the example on this repo (I added a button to show/hide the camera and tested in debug and release mode) and that's where I noticed that the differentiator is having Hermes enabled. In both my repo and this repo example, switching Hermes on causes the memory increase on iOS, after switching it off memory is allocated and released as expected.

My repo (debug mode) with hermes:

![ios-debug-with-hermes](https://user-images.githubusercontent.com/809537/174778394-9e7d8760-f43f-4f9b-8814-61f22dfbee77.png)

My repo (debug mode) without hermes:

![ios-debug-without-hermes](https://user-images.githubusercontent.com/809537/174778436-5c491b40-b385-4244-9057-38a0e21319b7.png)

This repo (release mode) with hermes:

![rnvc-with-hermes](https://user-images.githubusercontent.com/809537/174778614-a7136180-8644-41a3-b35c-497116e74e66.png)

I'm not really sure where to go from here, I have a feeling it may be related to reanimated as there are some [issues](https://github.com/software-mansion/react-native-reanimated/issues/2824) over there that look like they may be contributing.

**Comment by bglgwyng** [comment]
I think I found the minimal reproducing step. [Here](https://github.com/bglgwyng/RNVC3Sandbox/tree/memory-leak) is the repository.

[As you can see in the repo](https://github.com/bglgwyng/RNVC3Sandbox/blob/memory-leak/App.tsx#L26), `useFrameProcessor` recreates the frame processor on every change of `foo` value. 
I suppose that the object returned by `useFrameProcessor` is not being cleaned up well, and it causes the leak.

The example is with [V3](https://github.com/mrousavy/react-native-vision-camera/issues/1376). However, you can reproduce the leak in the same way with V2 also.

**Comment by mrousavy** [comment]
Hey thanks for your research @alexstanbury and thanks for your repro @bglgwyng - appreciate it!
I'll investigate this as part of the V3 efforts!

**Comment by scotjam** [comment]
I've been trying to write my first react native app using react-native-vision-camera, but my app has been crashing on android without leaving an error message at all (just disappears on the device - no sign in console that it has crashed). I eventually discovered that commenting out the frame processor from the Camera properties in the return value stops it from crashing so I suspect it is the same bug that this issue number refers to. 

Unfortunately I'm trying to do face detection (then use react-native-sound to play a sequence of sounds) so I need the frame processor for the face detection, but it almost never makes it to the end of the sound sequence. I suspect that this bug (1098) may be the same bug I'm facing, but I'm facing it on Android.

I tried reanimated 2.17.0 (as well as the reanimated 2.14.4 that I downgraded to initially, to get around this bug: https://github.com/mrousavy/react-native-vision-camera/issues/1514) and the issue still occurs. But as described in 1514, reanimated 3.x isn't supported by react-native-vision-camera (Property '_setGlobalConsole' doesn't exist) so I don't know if 3.x would fix the problem. 

In the meantime I have had to resort to using a different camera library for face recognition (which is playing nicely with react-native-sound fortunately, hence I'm pretty sure my issue is with using react-native-vision-camera and specifically it is the frame processor's fault, rather than react-native-sound). Would report this as a reanimated bug, but given they're on 3.x now it may have been fixed. 

So I'm posting this comment just so that if there are others who follow the same path I did, they don't get stuck thinking they've done something wrong (I spent hours trying to figure out whether I hadn't release()d a Sound object in some edge case). Unfortunately the current version of react-native-vision-camera relies on react-native-reanimated 2.x, and react-native-reanimated 2.x has memory leak bugs that affect android as well as iOS. 

Looking forward to V3 (without reanimated), and thanks for all your efforts!

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please let me know here!!

**Comment by GreenCurveDev** [comment]
Hi, I can confirm the issue is still present - running latest app versions and an 'empty' Frame Processor or Skia Frame Processor (with or without calls to 'render') results in leakage of ~0.1MB per second (measured using React Native Dev Menu Perf Monitor). Same leakage occurs when using this in a bare workflow created using an EAS server build deployed directly to a device (in this case an iPhone 12). Left to run with no other interaction for a period of 5-10 mins, all memory is consumed (iP12) and app crashes. Disaster (for me) as discovered in late stages of testing where Frame Processors are being used for simple but continuous augmentation of the camera feed (Saturation, Contrast etc) using shaders. If I could somehow access the camera texture then I could use a package such as expo-GL to achieve the same results without having to switch camera package. For example, expo-gl has a function to create a camera texture from the camera reference. Any suggestions on how to do this using for RNVC would be gratefully received - as it stands Frame Processors cannot be used for this (or perhaps any) use case involving prolonged running of a frame processor function, Thanks & regards, Paul

**Comment by GreenCurveDev** [comment]
https://github.com/user-attachments/assets/caacb3e8-2c03-4510-a43d-be7328ee3179

Just to be 100% sure - I downloaded RNVC 4.5.3 to create bare minimum repro. Used two frame Processors (see below) and attached video of memory increase using the first (no Skia frame processor shown below). The memory increase is much more rapid for Skia version but hopefully this illustrates the issue.

const NullFrameProcessor = useFrameProcessor((frame) => {
    'worklet';
    //console.log('Running NULL FP');
  }, [])

and for Skia

const NullSkiaFrameProcessor = useSkiaFrameProcessor((frame) => {
    'worklet';
    //console.log('Running NULL SKIA FP');
    frame.render();
  }, [])


"@shopify/react-native-skia": "^1.3.13", 
"react-native-vision-camera": "^4.5.3",
"react-native-worklets-core": "^1.3.3"

**Comment by astanb** [comment]
Interesting - Have you tried on both iOS and Android? Have you tried using a release build and monitoring in Xcode and Android Studio?

**Comment by mrousavy** [comment]
Hey! This is interesting. I had Frame Processors running for 30mins without any crashes.

Are you using the Reanimated babel plugin, or worklets-core only?

Pretty sure this will be fixed with [Nitro Modules](https://github.com/mrousavy/nitro) once I rewrite VisionCamera to be one.

**Comment by GreenCurveDev** [comment]
Hi, thanks to both.  Just run it via Xcode and monitored memory by enabling Malloc Scrabble etc - this shows the memory increasing in accordance with the behaviour observed using Perf Mon. 
I do have the reanimated plugin enabled but do not use it anywhere in the test code.  Will remove and rerun the test to see if that makes any difference - assume the 30m test was without the reanimated plugin. Will post result shortly.

**Comment by GreenCurveDev** [comment]
Hi, I have removed the Babel reanimated plugin and unfortunately the problem remains. When you ran for 30mins was the memory consumption roughly static? Thanks

**Comment by GreenCurveDev** [comment]
I think it would take 30+ mins to use all the memory as this is a bare bones app to test the issue - eventually however, I would expect all memory to be consumed and the app to fail.

**Comment by GreenCurveDev** [comment]
Actually, with a Skia frame processor and a single call to frame render - memory utilisation reaches 1GB is around 3-4 mins. So there must be something different between your 30min+ test and my own.

**Comment by GreenCurveDev** [comment]
maybe device settings/formats?

**Comment by dev-john-nguyen** [comment]
useFrameProcessor seems to be stable for me, but experiencing frequent crashing with useSkiaFrameProcessor. I posted a discussion about it in react-native-skia https://github.com/Shopify/react-native-skia/discussions/2675. I'm not able to yet pinpoint exactly where the issue is, but seems like gc is not properly releasing memory?

**Comment by JeremyColfer27** [comment]
> Actually, with a Skia frame processor and a single call to frame render - memory utilisation reaches 1GB is around 3-4 mins. So there must be something different between your 30min+ test and my own.

Did you ever find answers??
