### ISSUE TITLE
🐛 [V3][Android][CodeScanner] CodeScanner very slow on Android

### ISSUE THREAD

**Issue by spsaucier** [cuvent/react-native-vision-camera#1985]
### What's happening?

On a Moto G Stylus 2022 Android device, when `codeScanner` is used, the displayed view drops to about 5 fps and any `codeScanner` functionality is slow & delayed.

When codeScanner is disabled (or on iOS at all times), the framerate is excellent.

This is occurring on `react-native-vision-camera@3.3.1`.

### Reproduceable Code

```tsx
Tested in the Example App, with photo/video/audio/frameProcessor all disabled and this codeScanner function:


  const onCodeScanned = useCallback((codes: Code[]) => {
    console.log(codes.length)
  }, [])
```
```


### Relevant log output

```shell
N/A
```

### Camera Device

```json
{
  "sensorOrientation": "landscape-right",
  "hardwareLevel": "full",
  "maxZoom": 8,
  "minZoom": 1,
  "supportsLowLightBoost": false,
  "neutralZoom": 1,
  "physicalDevices": [
    "wide-angle-camera"
  ],
  "supportsFocus": true,
  "supportsRawCapture": true,
  "isMultiCam": false,
  "name": "BACK (0)",
  "hasFlash": true,
  "hasTorch": true,
  "position": "back",
  "id": "0"
}
```

### Device

Moto G Stylus 2022

### VisionCamera Version

3.3.1

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [x] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by irekrog** [comment]
Same issue on Samsung Galaxy A51

**Comment by FluffyDiscord** [comment]
can confirm, same on samsung galaxy s23 ultra

**Comment by GabrielvonPlaten** [comment]
Exact same issue here on a Samsung Galaxy S21 FE.

**Comment by zzz08900** [comment]
How about you guys change the title to "[V3][Android]" ? 
Putting iOS in the title of an Android-only problem gives me headaches.

**Comment by AlexDM0** [comment]
Same issue here on a samsung A23

**Comment by Danushka96** [comment]
Same Issue OnePlus 9. The first few seconds work fine, then start to drop the fps

**Comment by zzz08900** [comment]
FYI there's this frame processor plugin that works with v3:
https://github.com/mgcrea/vision-camera-barcode-scanner

I haven't fully tested myself but it looks pretty promising. Anyone hit by this issue could try using that plugin above on Android as a workaround. It utilizes MLKit on Android so the results should be same as the good old [vision-camera-code-scanner](https://github.com/rodgomesc/vision-camera-code-scanner) by [rodgomesc](https://github.com/rodgomesc/vision-camera-code-scanner)

**Comment by FluffyDiscord** [comment]
Yes, that one works nicely. I had to upgrade react native to 0.72.5 though.

**Comment by celik75** [comment]
same problem, pr fix of https://github.com/mrousavy/react-native-vision-camera/commit/915ef331d3b3f3630f4b8d5a8cdd7f5fcf30c335 didn't fixed it on android.

tested on 2 diffrent androids

**Comment by zzz08900** [comment]
> Yes, that one works nicely. I had to upgrade react native to 0.72.5 though.

Well I just tried it on Android and it crashed the whole app after ~1 sec of code scanning.
Guess I'll be staying with v2 a little longer.

Found what's wrong:
1. If you need reanimated and vision-camera frame processor to play nicely with each other, you'll need latest version of vision-camera, react-native-worklets-core, and react-native-reanimated
2. `babel.config.js` should look like this
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [['react-native-worklets-core/plugin'], ['react-native-reanimated/plugin']],
};
```

**Comment by mrousavy** [comment]
> same problem, pr fix of https://github.com/mrousavy/react-native-vision-camera/commit/915ef331d3b3f3630f4b8d5a8cdd7f5fcf30c335 didn't fixed it on android.
> tested on 2 diffrent androids

@celik75 how did you test that?

**Comment by sacha-c** [comment]
> > same problem, pr fix of https://github.com/mrousavy/react-native-vision-camera/commit/915ef331d3b3f3630f4b8d5a8cdd7f5fcf30c335 didn't fixed it on android.
> > tested on 2 diffrent androids
> 
> @celik75 how did you test that?

Also just tested using the [latest commit on main](https://github.com/mrousavy/react-native-vision-camera/commit/e8df7148fa50214f47ff1a41dfa40e7255bc3f8d) and the issue remains
I tested by using [gitpkg](https://gitpkg.vercel.app/) and setting my dependency to `https://gitpkg.now.sh/mrousavy/react-native-vision-camera/package?e8df7148fa50214f47ff1a41dfa40e7255bc3f8d`
I'm using an Xperia XZ Premium with Android 9
The behavior I noticed using this commit is that the camera is fluid at first but becomes _progressively_ laggy (during the first ~2 seconds) & it stabilizes with the same level of slowness as v3.3.1. On v3.3.1 however it was slow from the start

**Comment by mrousavy** [comment]
I don't get this. I think the Camera2 APIs are just terrible at this.

@sacha-c can you maybe try this change? Idk if that'll work better

![Screenshot 2023-10-16 at 13 19 08](https://github.com/mrousavy/react-native-vision-camera/assets/15199031/4619927c-59ab-4ffa-bf65-7c22cf75d8df)

**Comment by sacha-c** [comment]
@mrousavy Gave it a shot, and with this the lagging is fixed! It works smoothly and remains that way.

However after scanning a QR code the camera goes black, this did not used to occur on v3.3.1. 
Looking briefly through the logs I see this after scanning a QR code which may be related
```sh
2023-10-16 13:55:17.455  2699-3982  Camera3-OutputStream    cameraserver                         E  returnBufferCheckedLocked: Stream 0: Error queueing buffer to native window: No such device (-19)
2023-10-16 13:55:17.455  2699-3982  Camera3-Device          cameraserver                         E  Can't return buffer to its stream: No such device (-19)
```
It looks like it may be related to the latest codeScanning changes (not just the diff above, but the diff between v3.3.1..master), but if you would like a separate issue for this let me know if you would like me to create it.

**Comment by mrousavy** [comment]
Yea please create a separate issue. Thanks

**Comment by mrousavy** [comment]
Fixed this in #2009!

**Comment by spsaucier** [comment]
Render performance is much better now, thank you. Still seeing `onCodeScanned` buffer/queue and execute for a few seconds after the reads, but vastly improved!

**Comment by Danushka96** [comment]
Running smoothly on Android after the new version update (3.4.0)!

**Comment by mrousavy** [comment]
Amazing, great to hear my fix works for you guys.

> Still seeing onCodeScanned buffer/queue and execute for a few seconds after the reads, but vastly improved!

Create a separate issue if that's a problem, I don't quite get what this means tbh
