### ISSUE TITLE
🐛 codeScanner causes black screen on first camera start

### ISSUE THREAD

**Issue by dFelinger** [cuvent/react-native-vision-camera#2596]
### What's happening?

After upgrading from 3.9.0-beta.5 to 3.9.0-beta.6 there is black screen on first app start with codeScanner enabled. Without codeScanner in 3.9.0-beta.6 or with codeScanner but in 3.9.0-beta.5 there is no this issue.

https://github.com/mrousavy/react-native-vision-camera/assets/5339870/e7f05021-aab0-4620-ba53-96d73543b692

### Reproduceable Code

```tsx
function App() {
  const { hasPermission, requestPermission } = useCameraPermission();
  useEffect(() => {
    if (!hasPermission) {
      requestPermission();
    }
  }, [hasPermission, requestPermission]);

  const device = useCameraDevice('back');

  const [active, setActive] = useState(true);
  const toggle = () => {
    setActive(!active);
  };

  const codeScanner = useCodeScanner({
    codeTypes: ['qr', 'ean-13'],
    onCodeScanned: codes => {
      console.log(codes);
    },
  });

  if (device == null) {
    return <Text>No device</Text>;
  }

  if (!hasPermission) {
    return <Text>No hasPermission</Text>;
  }

  return (
    <View style={{ flex: 1 }}>
      <View style={{ alignItems: 'center', justifyContent: 'center' }}>
        <Text onPress={toggle}>TOGGLE ACTIVE {JSON.stringify(active)}</Text>
      </View>
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: 'red' }}>
        <Camera
          style={StyleSheet.absoluteFill}
          device={device}
          isActive={active}
          audio={false}
          photo={false}
          video={false}
          codeScanner={codeScanner}
          onError={e => {
            console.log('Error', e);
          }}
        />
      </View>
    </View>
  );
}
```

### Relevant log output

```shell
02-21 00:18:26.219 17346 17399 I ReactNativeJS: Running "testcamera" with {"rootTag":11}
02-21 00:18:26.233 17346 17412 D TrafficStats: tagSocket(134) with statsTag=0xffffffff, statsUid=-1
02-21 00:18:26.357 17346 17399 D CompatibilityChangeReporter: Compat change id reported: 250678880; UID 10192; state: ENABLED
02-21 00:18:26.365 17346 17399 D CompatibilityChangeReporter: Compat change id reported: 206033068; UID 10192; state: ENABLED
02-21 00:18:26.375   732   890 D EGL_emulation: app_time_stats: avg=15.46ms min=0.52ms max=49.55ms count=57
02-21 00:18:26.442 17346 17346 I PreviewView: Creating PreviewView...
02-21 00:18:26.443 17346 17346 I PreviewView: PreviewView is 0x0, rendering 1080x1920 content (LANDSCAPE_LEFT). Resizing to: 0x0 (COVER)
02-21 00:18:26.444 17346 17346 I CameraView: Updating CameraSession...
02-21 00:18:26.447 17346 17397 I CameraSession: configure { ... }: Waiting for lock...
02-21 00:18:26.448 17346 17397 I CameraSession: configure { ... }: Updating CameraSession Configuration... Difference(deviceChanged=true, outputsChanged=true, sidePropsChanged=true, isActiveChanged=true)
02-21 00:18:26.448 17346 17397 I CameraSession: Configuring inputs for CameraSession...
02-21 00:18:26.448 17346 17397 D PersistentCameraCaptureSession: --> setInput(10)
02-21 00:18:26.448 17346 17397 I CameraSession: Destroying previous outputs...
02-21 00:18:26.448 17346 17397 I CameraSession: Creating outputs for Camera #10...
02-21 00:18:26.450 17346 17397 I CameraSession: Adding 1280x720 CodeScanner Output in YUV_420_888...
02-21 00:18:26.496 17346 17414 D TransportRuntime.JobInfoScheduler: Upload for context TransportContext(cct, DEFAULT, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
02-21 00:18:26.498 17346 17414 D TransportRuntime.JobInfoScheduler: Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
02-21 00:18:26.506 17346 17346 I CameraView: Updating CameraSession...
02-21 00:18:26.507 17346 17346 I PreviewView: PreviewView is 1080x2035, rendering 1080x1920 content (LANDSCAPE_LEFT). Resizing to: 1145x2035 (COVER)
02-21 00:18:26.510 17346 17346 I CameraSession: PreviewView Surface created! Surface(name=null)/@0x79d2f9a
02-21 00:18:26.510 17346 17346 I CameraSession: Setting Preview Output...
02-21 00:18:26.511 17346 17346 I CameraSession: PreviewView Surface updated! Surface(name=null)/@0x79d2f9a 1920 x 1080
02-21 00:18:26.518 17346 17400 D CompatibilityChangeReporter: Compat change id reported: 289878283; UID 10192; state: ENABLED
02-21 00:18:26.519 17346 17417 I DynamiteModule: Considering local module com.google.mlkit.dynamite.barcode:10000 and remote module com.google.mlkit.dynamite.barcode:0
02-21 00:18:26.527 17346 17417 I DynamiteModule: Selected local version of com.google.mlkit.dynamite.barcode
02-21 00:18:26.563   326   375 I netd    : tetherGetStats() -> {[]} <0.18ms>
02-21 00:18:26.567   326   375 I netd    : bandwidthSetGlobalAlert(2097152) <0.06ms>
02-21 00:18:26.568   326   375 I netd    : bandwidthRemoveInterfaceQuota(eth0) <0.26ms>
02-21 00:18:26.568   326   375 I netd    : bandwidthSetInterfaceQuota(eth0, 9223372036854775807) <0.22ms>
02-21 00:18:26.678 17346 17397 D CompatibilityChangeReporter: Compat change id reported: 236825255; UID 10192; state: ENABLED
02-21 00:18:26.679 17346 17397 D PersistentCameraCaptureSession: --> setOutputs([VIDEO (1280 x 720 CodeScanner for [QR, EAN_13] (35))])
02-21 00:18:26.679 17346 17397 I CameraSession: Successfully configured Session with 1 outputs for Camera #10!
02-21 00:18:26.680 17346 17397 D PersistentCameraCaptureSession: --> setRepeatingRequest(...)
02-21 00:18:26.680 17346 17397 D PersistentCameraCaptureSession: --> setIsActive(false)
02-21 00:18:26.680 17346 17397 D PersistentCameraCaptureSession: Configure() with isActive: false, ID: 10, device: null, session: null
02-21 00:18:26.680 17346 17397 I PersistentCameraCaptureSession: Creating new device...
02-21 00:18:26.681 17346 17397 I CameraManager: Camera #10: Opening...
02-21 00:18:26.683   520  1812 W System.err: java.lang.SecurityException: Caller with uid 1047 is not android
02-21 00:18:26.683   520  1812 W System.err: 	at com.android.server.devicepolicy.DevicePolicyManagerService.getCallerIdentity(DevicePolicyManagerService.java:2368)
02-21 00:18:26.683   520  1812 W System.err: 	at com.android.server.devicepolicy.DevicePolicyManagerService.getCameraDisabled(DevicePolicyManagerService.java:9311)
02-21 00:18:26.683   520  1812 W System.err: 	at android.app.admin.DevicePolicyManager.getCameraDisabled(DevicePolicyManager.java:8423)
02-21 00:18:26.683   520  1812 W System.err: 	at com.android.server.camera.CameraServiceProxy$2.isCameraDisabled(CameraServiceProxy.java:622)
02-21 00:18:26.683   520  1812 W System.err: 	at android.hardware.ICameraServiceProxy$Stub.onTransact(ICameraServiceProxy.java:174)
02-21 00:18:26.683   520  1812 W System.err: 	at android.os.Binder.execTransactInternal(Binder.java:1344)
02-21 00:18:26.683   520  1812 W System.err: 	at android.os.Binder.execTransact(Binder.java:1275)
02-21 00:18:26.683   417  4226 I CameraService: CameraService::connect call (PID 17346 "com.testcamera", camera ID 10) and Camera API version 2
02-21 00:18:26.684   417  4226 I Camera2ClientBase: Camera 10: Opened. Client: com.testcamera (PID 17346, UID 10192)
02-21 00:18:26.684   417  4226 I CameraDeviceClient: CameraDeviceClient 10: Opened
02-21 00:18:26.684   417  4226 I CameraService: makeClient: Camera2 API, override to portrait 1
02-21 00:18:26.685 17346 17400 I CameraDevices: Camera #10 is now unavailable.
02-21 00:18:26.686   520  1812 V CameraService_proxy: Disable Rotate and Crop to avoid conflicts with WM force rotation treatment.
02-21 00:18:26.687   417  4226 D cameraserver: FGS Logger Transaction failed
02-21 00:18:26.689   417  4226 D cameraserver: -129
02-21 00:18:26.691 17346 17398 I CameraManager: Camera #10: Opened!
02-21 00:18:26.691 17346 17397 I CameraSession: configure { ... }: Waiting for lock...
02-21 00:18:26.692 17346 17397 I CameraSession: configure { ... }: Waiting for lock...
02-21 00:18:26.692 17346 17397 I PersistentCameraCaptureSession: Creating new session...
02-21 00:18:26.693 17346 17397 I CreateCaptureSession: Camera #10: Creating Capture Session #1... (Hardware Level: 0 | Outputs: [VIDEO (1280 x 720 CodeScanner for [QR, EAN_13] (35))])
02-21 00:18:26.694 17346 17397 I CreateCaptureSession: Using new API (>=28)
02-21 00:18:26.694   331   331 D camera.provider.ranchu: CameraDeviceSession:configureStreams:176 cfg={ .streams.size=1, .operationMode=0, .cfg.sessionParams.size()=64,  .streamConfigCounter=1, .multiResolutionInputImage=false }
02-21 00:18:26.694   331   331 D camera.provider.ranchu: CameraDeviceSession:configureStreams:199 stream={ .id=0, .streamType=0, .width=1280, .height=720, .format=YCBCR_420_888, .usage=0x3, .dataSpace={ .low=0x0, .s=2, .t=3, .r=1 }, .rotation=0, .physicalCameraId='', .bufferSize=0, .groupId=-1, .dynamicRangeProfile=0x1 }
02-21 00:18:26.957 17346 17415 W com.testcamera: Verification of void com.google.android.gms.internal.mlkit_vision_barcode.zznj.configure(com.google.firebase.encoders.config.EncoderConfig) took 279.136ms (4116.26 bytecodes/s) (43416B approximate peak alloc)
02-21 00:18:26.968 17346 17414 D TransportRuntime.SQLiteEventStore: Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
02-21 00:18:26.973 17346 17414 D TransportRuntime.JobInfoScheduler: Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
02-21 00:18:26.976 17346 17414 D TransportRuntime.SQLiteEventStore: Storing event with priority=DEFAULT, name=FIREBASE_ML_SDK for destination cct
02-21 00:18:26.978 17346 17414 D TransportRuntime.JobInfoScheduler: Upload for context TransportContext(cct, DEFAULT, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
02-21 00:18:26.983   417  4226 D Camera3-Device: Set real time priority for request queue thread (tid 17425)
02-21 00:18:26.983 17346 17398 I CreateCaptureSession: Camera #10: Successfully created CameraCaptureSession #1!
02-21 00:18:26.983 17346 17397 D PersistentCameraCaptureSession: Stopping repeating request...
02-21 00:18:26.984 17346 17397 D PersistentCameraCaptureSession: Configure() done! isActive: false, ID: 10, device: android.hardware.camera2.impl.CameraDeviceImpl@c583218, session: android.hardware.camera2.impl.CameraCaptureSessionImpl@760d471
02-21 00:18:26.984 17346 17397 I CameraSession: configure { ... }: Completed CameraSession Configuration! (isActive: false, isRunning: false)
02-21 00:18:26.984 17346 17397 I CameraView: invokeOnInitialized()
02-21 00:18:26.984 17346 17397 I CameraSession: configure { ... }: Updating CameraSession Configuration... Difference(deviceChanged=false, outputsChanged=false, sidePropsChanged=false, isActiveChanged=true)
02-21 00:18:26.985 17346 17397 D PersistentCameraCaptureSession: --> setIsActive(false)
02-21 00:18:26.985 17346 17397 D PersistentCameraCaptureSession: Configure() with isActive: false, ID: 10, device: android.hardware.camera2.impl.CameraDeviceImpl@c583218, session: android.hardware.camera2.impl.CameraCaptureSessionImpl@760d471
02-21 00:18:26.985 17346 17397 D PersistentCameraCaptureSession: Stopping repeating request...
02-21 00:18:26.985 17346 17397 D PersistentCameraCaptureSession: Configure() done! isActive: false, ID: 10, device: android.hardware.camera2.impl.CameraDeviceImpl@c583218, session: android.hardware.camera2.impl.CameraCaptureSessionImpl@760d471
02-21 00:18:26.985 17346 17397 I CameraSession: configure { ... }: Completed CameraSession Configuration! (isActive: true, isRunning: false)
02-21 00:18:26.985 17346 17397 I CameraSession: configure { ... }: Updating CameraSession Configuration... Difference(deviceChanged=false, outputsChanged=true, sidePropsChanged=true, isActiveChanged=true)
02-21 00:18:26.985 17346 17397 I CameraSession: Destroying previous outputs...
02-21 00:18:26.986 17346 17397 I SurfaceOutput: Closing BarcodeScanner..
02-21 00:18:26.986 17346 17397 I CameraSession: Creating outputs for Camera #10...
02-21 00:18:26.990 17346 17397 I CameraSession: Adding 1280x960 Preview Output...
02-21 00:18:26.992 17346 17414 D TransportRuntime.SQLiteEventStore: Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
02-21 00:18:26.994 17346 17346 I SurfaceHolder: Resizing SurfaceHolder to 1280 x 960...
02-21 00:18:26.994 17346 17414 D TransportRuntime.JobInfoScheduler: Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
02-21 00:18:27.542 17346 17429 D TrafficStats: tagSocket(145) with statsTag=0x90000, statsUid=-1
02-21 00:18:27.544   326 17430 I resolv  : GetAddrInfoHandler::run: {101 101 101 983141 10192 0}
02-21 00:18:27.576   732   732 D StatusBarIconController: ignoring old pipeline callback because the new wifi icon is enabled
02-21 00:18:27.838   520  1452 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
02-21 00:18:27.905   329  1937 D android.hardware.audio@7.1-impl.ranchu: threadLoop: entering standby, frames: 28654656
02-21 00:18:29.553 17346 17431 D TrafficStats: tagSocket(145) with statsTag=0x90000, statsUid=-1
02-21 00:18:29.556   326 17432 I resolv  : GetAddrInfoHandler::run: {101 101 101 983141 10192 0}
02-21 00:18:31.568 17346 17433 D TrafficStats: tagSocket(145) with statsTag=0x90000, statsUid=-1
02-21 00:18:31.572   326 17434 I resolv  : GetAddrInfoHandler::run: {101 101 101 983141 10192 0}
```

### Camera Device

```json
{
  "formats": [],
  "sensorOrientation": "landscape-left",
  "hardwareLevel": "limited",
  "maxZoom": 1,
  "minZoom": 1,
  "maxExposure": 6,
  "supportsLowLightBoost": false,
  "neutralZoom": 1,
  "physicalDevices": [
    "ultra-wide-angle-camera"
  ],
  "supportsFocus": false,
  "supportsRawCapture": false,
  "isMultiCam": false,
  "minFocusDistance": 999.999985098839,
  "minExposure": -6,
  "name": "BACK (10)",
  "hasFlash": false,
  "hasTorch": false,
  "position": "back",
  "id": "10"
}
```

### Device

Android emulator Pixel_3a_API_34_extension_level_7_arm64-v8a

### VisionCamera Version

3.9.0-beta.6

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by Saidnazar08** [comment]
I have the same issue, but in my case when I use the format prop with the useCameraFormat.

**Comment by nhatduy51** [comment]
same issue

**Comment by mrousavy** [comment]
Hey! I just released a new V4 beta ([v4.0.0-beta.7](https://github.com/mrousavy/react-native-vision-camera/releases/tag/v4.0.0-beta.7)) where I fixed a bunch of issues! 💪🚀 Can you test that and see if that fixes the issue for you? 😅 

```
yarn add react-native-vision-camera@beta
```

You might need to increase the `compileSdk` to the newest Android SDK (34) if you are behind.

**Comment by dFelinger** [comment]
No black screen at start! But codeScanner triggering only once and if code is in preview on camera start. Tested in example app v4.0.0-beta.8

https://github.com/mrousavy/react-native-vision-camera/assets/5339870/ce5f91a3-982b-4db8-b588-2ed5dec19d51

**Comment by thib-info** [comment]
Hello @dFelinger, I'm also using the QR code scanner feature of the package and faced the black screen error also.
I've only tested on real hardware and not on emulator. I'm facing this issue on some phones, but not all of them. 

Have you also tried on real devices or not ?

**Comment by dFelinger** [comment]
I'm using 3.9.0-beta.5 version. There is no black screen on emulator and real devices. Tested on 2 real devices.

**Comment by mrousavy** [comment]
QR Code issue is fixed in latest V4 beta! :)

**Comment by thib-info** [comment]
Hello back, I can confirm you @mrousavy that's on the new beta, the scanner and the access of the camera is now working !!! However, I still have a black screen after minimizing the app and opening it again. 
Do you have any ideas of where that could come from ?

**Comment by mrousavy** [comment]
Thanks guys, great to hear that V4 now works pretty well! If you appreciate my work, please consider [💖 sponsoring me on GitHub 💖](http://github.com/sponsors/mrousavy/) so I can keep maintaining this library, fixing bugs and building new features! :)

> !!! However, I still have a black screen after minimizing the app and opening it again.

Hm, not sure. I'd have to spend time investigating that.
