### ISSUE TITLE
Video={true}, the camera does not load. 4.0.0-beta.5

### ISSUE THREAD

**Issue by sberkeo** [cuvent/react-native-vision-camera#2651]
### What's happening?

When you try to change the camera direction to back to front or front to back when video={true}, the camera does not load. It works fine only when photo={true}.

### Reproduceable Code

```tsx
<Camera
                    key={cameraKey}
                    style={
                        isCameraInitialized
                            ? {
                                position: "absolute",
                                top: 0,
                                left: 0,
                                right: 0,
                                bottom: 0,
                                ...StyleSheet.absoluteFill, zIndex: isVisionCameraActive ? 995 : -9, flex: 1, width: windowWidth, height: windowHeight
                            }
                            : {
                                width: 0,
                                height: 0,
                            }
                    }
                    //style={{ ...StyleSheet.absoluteFill, zIndex: isVisionCameraActive ? 995 : -9, flex: 1, width: windowWidth, height: windowHeight, }}
                    ref={cameravision}
                    device={device}
                    photo={true}
                    //video={true}
                    //audio={true}
                    //pixelFormat="native"
                    //resizeMode="contain"
                    fps={fps}
                    videoHdr={hdrMode}
                    photoHdr={hdrMode}
                    lowLightBoost={device.supportsLowLightBoost ? lowlightMode : false}
                    videoStabilizationMode={format.videoStabilizationModes.includes('cinematic-extended') ? videostabilizationMode : 'off'}
                    enableHighQualityPhotos
                    enableZoomGesture
                    isActive={isVisionCameraActive}
                    focusable={true}
                    orientation={'portrait'}
                    format={format}
                    onInitialized={() => {

                        if (!isCameraInitialized) {
                            // Kamera başlatılmamışsa ve platform iOS değilse
                            setTimeout(() => {
                                setIsCameraInitialized(true);
                            }, 50);
                        }

                    }}

                />
```

### Relevant log output

```shell
03-12 23:01:09.688 13544 13544 E unknown:com.facebook.react.uimanager.UIManagerHelper:  at com.mrousavy.camera.CameraView_EventsKt.sendEvent(CameraView+Events.kt:124)
03-12 23:01:09.688 13544 13544 E unknown:com.facebook.react.uimanager.UIManagerHelper:  at com.mrousavy.camera.CameraView_EventsKt.invokeOnError(CameraView+Events.kt:69)
03-12 23:01:09.688 13544 13544 E unknown:com.facebook.react.uimanager.UIManagerHelper:  at com.mrousavy.camera.CameraView.onError(CameraView.kt:278)
03-12 23:01:09.688 13544 13544 E unknown:com.facebook.react.uimanager.UIManagerHelper:  at com.mrousavy.camera.core.CameraSession$configureCamera$3.invoke(CameraSession.kt:387)
03-12 23:01:09.688 13544 13544 E unknown:com.facebook.react.uimanager.UIManagerHelper:  at com.mrousavy.camera.core.CameraSession$configureCamera$3.invoke(CameraSession.kt:375)
03-12 23:01:09.688 13544 13544 E unknown:com.facebook.react.uimanager.UIManagerHelper:  at com.mrousavy.camera.core.CameraSession.configureCamera$lambda$8(CameraSession.kt:375)
03-12 23:01:09.688 13544 13544 E unknown:com.facebook.react.uimanager.UIManagerHelper:  at com.mrousavy.camera.core.CameraSession.$r8$lambda$4Z3XBXeZe7nK1umYnjsgdpFZMVY(Unknown Source:0)
03-12 23:01:09.688 13544 13544 E unknown:com.facebook.react.uimanager.UIManagerHelper:  at com.mrousavy.camera.core.CameraSession$$ExternalSyntheticLambda1.onChanged(Unknown Source:2)
03-12 23:01:09.688 13544 13544 E unknown:com.facebook.react.uimanager.UIManagerHelper:  at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
03-12 23:01:09.688 13544 13544 E unknown:com.facebook.react.uimanager.UIManagerHelper:  at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
03-12 23:01:09.688 13544 13544 E unknown:com.facebook.react.uimanager.UIManagerHelper:  at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
03-12 23:01:09.688 13544 13544 E unknown:com.facebook.react.uimanager.UIManagerHelper:  at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
03-12 23:01:09.688 13544 13544 E unknown:com.facebook.react.uimanager.UIManagerHelper:  at androidx.camera.camera2.internal.Camera2CameraInfoImpl$RedirectableLiveData.$r8$lambda$LuOJQ0sg1wvLyxomp0-YWy0I_2g(Unknown Source:0)
03-12 23:01:09.688 13544 13544 E unknown:com.facebook.react.uimanager.UIManagerHelper:  at androidx.camera.camera2.internal.Camera2CameraInfoImpl$RedirectableLiveData$$ExternalSyntheticLambda0.onChanged(Unknown Source:2)
03-12 23:01:09.688 13544 13544 E unknown:com.facebook.react.uimanager.UIManagerHelper:  at androidx.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:152)
03-12 23:01:09.688 13544 13544 E unknown:com.facebook.react.uimanager.UIManagerHelper:  at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
03-12 23:01:09.688 13544 13544 E unknown:com.facebook.react.uimanager.UIManagerHelper:  at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
03-12 23:01:09.688 13544 13544 E unknown:com.facebook.react.uimanager.UIManagerHelper:  at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
03-12 23:01:09.688 13544 13544 E unknown:com.facebook.react.uimanager.UIManagerHelper:  at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
03-12 23:01:09.688 13544 13544 E unknown:com.facebook.react.uimanager.UIManagerHelper:  at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
03-12 23:01:09.688 13544 13544 E unknown:com.facebook.react.uimanager.UIManagerHelper:  at android.os.Handler.handleCallback(Handler.java:938)
03-12 23:01:09.688 13544 13544 E unknown:com.facebook.react.uimanager.UIManagerHelper:  at android.os.Handler.dispatchMessage(Handler.java:99)
03-12 23:01:09.688 13544 13544 E unknown:com.facebook.react.uimanager.UIManagerHelper:  at android.os.Looper.loop(Looper.java:246)
03-12 23:01:09.688 13544 13544 E unknown:com.facebook.react.uimanager.UIManagerHelper:  at android.app.ActivityThread.main(ActivityThread.java:8653)
03-12 23:01:09.688 13544 13544 E unknown:com.facebook.react.uimanager.UIManagerHelper:  at java.lang.reflect.Method.invoke(Native Method)
03-12 23:01:09.688 13544 13544 E unknown:com.facebook.react.uimanager.UIManagerHelper:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
03-12 23:01:09.688 13544 13544 E unknown:com.facebook.react.uimanager.UIManagerHelper:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
03-12 23:01:09.689 13544 13544 I CameraSession39: Camera State: OPEN (has error: true)
03-12 23:01:09.689 13544 13544 E CameraView: invokeOnError(...):
03-12 23:01:09.689 13544 13544 W System.err: com.mrousavy.camera.core.InvalidOutputConfigurationError: Failed to configure the Camera Session because the output/stream configurations are invalid!
03-12 23:01:09.689 13544 13544 W System.err:    at com.mrousavy.camera.extensions.StateError_toCameraErrorKt.toCameraError(StateError+toCameraError.kt:23)
03-12 23:01:09.689 13544 13544 W System.err:    at com.mrousavy.camera.core.CameraSession$configureCamera$3.invoke(CameraSession.kt:387)
03-12 23:01:09.689 13544 13544 W System.err:    at com.mrousavy.camera.core.CameraSession$configureCamera$3.invoke(CameraSession.kt:375)
03-12 23:01:09.689 13544 13544 W System.err:    at com.mrousavy.camera.core.CameraSession.configureCamera$lambda$8(CameraSession.kt:375)
03-12 23:01:09.689 13544 13544 W System.err:    at com.mrousavy.camera.core.CameraSession.$r8$lambda$4Z3XBXeZe7nK1umYnjsgdpFZMVY(Unknown Source:0)
03-12 23:01:09.689 13544 13544 W System.err:    at com.mrousavy.camera.core.CameraSession$$ExternalSyntheticLambda1.onChanged(Unknown Source:2)
03-12 23:01:09.689 13544 13544 W System.err:    at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)        
03-12 23:01:09.689 13544 13544 W System.err:    at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)      
03-12 23:01:09.689 13544 13544 W System.err:    at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
03-12 23:01:09.689 13544 13544 W System.err:    at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50) 
03-12 23:01:09.690 13544 13544 W System.err:    at androidx.camera.camera2.internal.Camera2CameraInfoImpl$RedirectableLiveData.$r8$lambda$LuOJQ0sg1wvLyxomp0-YWy0I_2g(Unknown Source:0)
03-12 23:01:09.690 13544 13544 W System.err:    at androidx.camera.camera2.internal.Camera2CameraInfoImpl$RedirectableLiveData$$ExternalSyntheticLambda0.onChanged(Unknown Source:2)
03-12 23:01:09.690 13544 13544 W System.err:    at androidx.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:152)
03-12 23:01:09.690 13544 13544 W System.err:    at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)        
03-12 23:01:09.690 13544 13544 W System.err:    at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)      
03-12 23:01:09.690 13544 13544 W System.err:    at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
03-12 23:01:09.690 13544 13544 W System.err:    at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50) 
03-12 23:01:09.690 13544 13544 W System.err:    at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
03-12 23:01:09.690 13544 13544 W System.err:    at android.os.Handler.handleCallback(Handler.java:938)
03-12 23:01:09.690 13544 13544 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
03-12 23:01:09.690 13544 13544 W System.err:    at android.os.Looper.loop(Looper.java:246)
03-12 23:01:09.690 13544 13544 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:8653)
03-12 23:01:09.690 13544 13544 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
03-12 23:01:09.690 13544 13544 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
03-12 23:01:09.690 13544 13544 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)        
03-12 23:01:09.690 13544 13544 W System.err: Caused by: java.util.concurrent.TimeoutException: Future[androidx.camera.core.impl.utils.futures.ListFuture@44ee85a] is not done within 5000 ms.
03-12 23:01:09.690 13544 13544 W System.err:    at androidx.camera.core.impl.utils.futures.Futures.lambda$makeTimeoutFuture$1(Futures.java:439)
03-12 23:01:09.690 13544 13544 W System.err:    at androidx.camera.core.impl.utils.futures.Futures$$ExternalSyntheticLambda0.call(Unknown Source:6)
03-12 23:01:09.690 13544 13544 W System.err:    at androidx.camera.core.impl.utils.executor.HandlerScheduledExecutorService$HandlerScheduledFuture.run(HandlerScheduledExecutorService.java:245)
03-12 23:01:09.690 13544 13544 W System.err:    at android.os.Handler.handleCallback(Handler.java:938)
03-12 23:01:09.690 13544 13544 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
03-12 23:01:09.690 13544 13544 W System.err:    at android.os.Looper.loop(Looper.java:246)
03-12 23:01:09.690 13544 13544 W System.err:    at android.os.HandlerThread.run(HandlerThread.java:67)
03-12 23:01:09.693 13544 13544 I CameraSession39: Camera State: OPEN (has error: true)
03-12 23:01:09.693 13544 13544 E CameraView: invokeOnError(...):
03-12 23:01:09.693 13544 13544 W System.err: com.mrousavy.camera.core.InvalidOutputConfigurationError: Failed to configure the Camera Session because the output/stream configurations are invalid!
03-12 23:01:09.693 13544 13544 W System.err:    at com.mrousavy.camera.extensions.StateError_toCameraErrorKt.toCameraError(StateError+toCameraError.kt:23)
03-12 23:01:09.693 13544 13544 W System.err:    at com.mrousavy.camera.core.CameraSession$configureCamera$3.invoke(CameraSession.kt:387)
03-12 23:01:09.693 13544 13544 W System.err:    at com.mrousavy.camera.core.CameraSession$configureCamera$3.invoke(CameraSession.kt:375)
03-12 23:01:09.693 13544 13544 W System.err:    at com.mrousavy.camera.core.CameraSession.configureCamera$lambda$8(CameraSession.kt:375)
03-12 23:01:09.694 13544 13544 W System.err:    at com.mrousavy.camera.core.CameraSession.$r8$lambda$4Z3XBXeZe7nK1umYnjsgdpFZMVY(Unknown Source:0)
03-12 23:01:09.694 13544 13544 W System.err:    at com.mrousavy.camera.core.CameraSession$$ExternalSyntheticLambda1.onChanged(Unknown Source:2)
03-12 23:01:09.694 13544 13544 W System.err:    at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)        
03-12 23:01:09.694 13544 13544 W System.err:    at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)      
03-12 23:01:09.694 13544 13544 W System.err:    at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
03-12 23:01:09.694 13544 13544 W System.err:    at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50) 
03-12 23:01:09.694 13544 13544 W System.err:    at androidx.camera.camera2.internal.Camera2CameraInfoImpl$RedirectableLiveData.$r8$lambda$LuOJQ0sg1wvLyxomp0-YWy0I_2g(Unknown Source:0)
03-12 23:01:09.694 13544 13544 W System.err:    at androidx.camera.camera2.internal.Camera2CameraInfoImpl$RedirectableLiveData$$ExternalSyntheticLambda0.onChanged(Unknown Source:2)
03-12 23:01:09.694 13544 13544 W System.err:    at androidx.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:152)
03-12 23:01:09.694 13544 13544 W System.err:    at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)        
03-12 23:01:09.694 13544 13544 W System.err:    at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)      
03-12 23:01:09.694 13544 13544 W System.err:    at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
03-12 23:01:09.694 13544 13544 W System.err:    at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50) 
03-12 23:01:09.694 13544 13544 W System.err:    at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
03-12 23:01:09.694 13544 13544 W System.err:    at android.os.Handler.handleCallback(Handler.java:938)
03-12 23:01:09.694 13544 13544 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
03-12 23:01:09.694 13544 13544 W System.err:    at android.os.Looper.loop(Looper.java:246)
03-12 23:01:09.694 13544 13544 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:8653)
03-12 23:01:09.694 13544 13544 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
03-12 23:01:09.694 13544 13544 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
03-12 23:01:09.694 13544 13544 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)        
03-12 23:01:09.694 13544 13544 W System.err: Caused by: java.util.concurrent.TimeoutException: Future[androidx.camera.core.impl.utils.futures.ListFuture@44ee85a] is not done within 5000 ms.
03-12 23:01:09.694 13544 13544 W System.err:    at androidx.camera.core.impl.utils.futures.Futures.lambda$makeTimeoutFuture$1(Futures.java:439)
03-12 23:01:09.694 13544 13544 W System.err:    at androidx.camera.core.impl.utils.futures.Futures$$ExternalSyntheticLambda0.call(Unknown Source:6)
03-12 23:01:09.694 13544 13544 W System.err:    at androidx.camera.core.impl.utils.executor.HandlerScheduledExecutorService$HandlerScheduledFuture.run(HandlerScheduledExecutorService.java:245)
03-12 23:01:09.695 13544 13544 W System.err:    at android.os.Handler.handleCallback(Handler.java:938)
03-12 23:01:09.695 13544 13544 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
03-12 23:01:09.695 13544 13544 W System.err:    at android.os.Looper.loop(Looper.java:246)
03-12 23:01:09.695 13544 13544 W System.err:    at android.os.HandlerThread.run(HandlerThread.java:67)
03-12 23:01:09.725 13544 32622 E ReactNativeJS: 'Camera.onError(session/invalid-output-configuration): Failed to configure the Camera Session because the output/stream configurations are invalid!', { [session/invalid-output-configuration: Failed to configure the Camera Session because the output/stream configurations are invalid!]
03-12 23:01:09.725 13544 32622 E ReactNativeJS:   name: 'session/invalid-output-configuration',
03-12 23:01:09.725 13544 32622 E ReactNativeJS:   _code: 'session/invalid-output-configuration',
03-12 23:01:09.725 13544 32622 E ReactNativeJS:   _message: 'Failed to configure the Camera Session because the output/stream configurations are invalid!',
03-12 23:01:09.725 13544 32622 E ReactNativeJS:   _cause:
03-12 23:01:09.725 13544 32622 E ReactNativeJS:    { stacktrace: 'java.util.concurrent.TimeoutException: Future[androidx.camera.core.impl.utils.futures.ListFuture@44ee85a] is not done within 5000 ms.\n\tat androidx.camera.core.impl.utils.futures.Futures.lambda$makeTimeoutFuture$1(Futures.java:439)\n\tat androidx.camera.core.impl.utils.futures.Futures$$ExternalSyntheticLambda0.call(Unknown Source:6)\n\tat androidx.camera.core.impl.utils.executor.HandlerScheduledExecutorService$HandlerScheduledFuture.run(HandlerScheduledExecutorService.java:245)\n\tat android.os.Handler.handleCallback(Handler.java:938)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loop(Looper.java:246)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\n',
03-12 23:01:09.725 13544 32622 E ReactNativeJS:      message: 'Future[androidx.camera.core.impl.utils.futures.ListFuture@44ee85a] is not done within 5000 ms.' } }
03-12 23:01:09.874   989  1855 D SemWifiSwitchForIndividualAppsService: isSkipNetworkCondition - result:1
03-12 23:01:10.136   773  1445 D qmi_secgps_clnt: SECGPS: QMI_SECGPS_AGNSS_CONFIG_MESSAGE_IND_V01 received
03-12 23:01:10.142  2779  2887 W QcomMsgHandler_FLP: Not used msg : RPUSH/00092
03-12 23:01:10.186   989  1841 I SemDvfsHyPerManager: acquire hyper - WIFI_CSTATE/989@12, type = 268447744
03-12 23:01:10.187   781   804 I HYPER-HAL: [RequestManager.cpp]acquire(): Acquired ID : 501513  [989 / 12]    HINT :      list : [LPMDisable / 1] [TIMEOUT / 2000]
03-12 23:01:10.199   773  1443 W LocSvc_ApiV02: reportSv:3861] At least one RF_LOSS is 0 in gps.conf, please configure it
03-12 23:01:10.201   989  1824 D GnssLocationProvider: WakeLock acquired by sendMessage(REPORT_SV_STATUS, 0, com.android.server.location.gnss.GnssLocationProvider$SvStatusInfo@7563316)
03-12 23:01:10.202   989  1804 D GnssLocationProvider_ex: SV Count : 0 / 2      (PRN, Constellation, SNR, Used)
03-12 23:01:10.202   989  1804 D GnssLocationProvider_ex: (3, GPS, 26,3, 0) (6, GLONASS, 25,5, 0)
03-12 23:01:10.203   989  1804 D GnssLocationProvider: WakeLock released by handleMessage(REPORT_SV_STATUS, 0, com.android.server.location.gnss.GnssLocationProvider$SvStatusInfo@7563316)
03-12 23:01:10.208  2779  2887 I GnssEngineManager_FLP: updateSatelliteStatus, top4=25, top6=25, visibleSv=2, usedSv=0, usedL5Sv=0 (usedGps=0, usedGlo=0, usedBds=0, usedGal=0)
03-12 23:01:10.363   989  1357 E ThermalHalWrapper: Couldn't get temperatures because of HAL error: Failed to read data
03-12 23:01:10.364   989  1357 E ThermalHalWrapper: Couldn't get temperatures because of HAL error: Failed to read data 
03-12 23:01:10.365   989  1357 E ThermalHalWrapper: Couldn't get temperatures because of HAL error: Failed to read data 
03-12 23:01:10.369   989  1357 E ThermalHalWrapper: Couldn't get temperatures because of HAL error: Failed to read data 
03-12 23:01:10.410  1207 25016 I bauth_FPBAuthService: pcf : 0x1011, 0 ,3 ,2 ,1 ,1 ,0, 5.1.0.0
03-12 23:01:10.411  1207 25016 E bauth_FPBAuthService: skip cleanup here 2
03-12 23:01:10.411  1207 25016 I bauth_FPBAuthService: thread id : 3, preenroll_flag : 0, nd cnt : 0, cso : 0, et : 0   
03-12 23:01:10.411  1207 25016 I bauth_FPBAuthService: FPBAuthService, 11607
03-12 23:01:10.479   628   628 I io_stats: !@   8,0 r 10386623 297984864 w 4115161 170722544 d 468499 157104944 f 881809 1333560 iot 6470580 5818487 th 102400 102400 64088 pt 70790 inp 0 0 154198.952
```

### Camera Device

```json
{
  "formats": [],
  "sensorOrientation": "landscape-left",
  "hardwareLevel": "full",
  "maxZoom": 8,
  "minZoom": 1,
  "maxExposure": 20,
  "supportsLowLightBoost": false,
  "neutralZoom": 1,
  "physicalDevices": [
    "wide-angle-camera"
  ],
  "supportsFocus": true,
  "supportsRawCapture": false,
  "isMultiCam": false,
  "minFocusDistance": 10,
  "minExposure": -20,
  "name": "0 (BACK) androidx.camera.camera2",
  "hasFlash": true,
  "hasTorch": true,
  "position": "back",
  "id": "0"
}
```

### Device

Samsung Galaxy A70 (Android 11)

### VisionCamera Version

4.0.0-beta.5

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Fixed in https://github.com/mrousavy/react-native-vision-camera/commit/5283020840751d174a3f82a97ceea78b875cc5d5! 💪🥳

**Comment by sberkeo** [comment]
Thank you for your solution, but unfortunately the problem still persists.

**Comment by mrousavy** [comment]
well, I don't know. I already spent too much time on this (about 2 weeks just for this bug) so I'm not sure what else to try. Also it seems like no one wants to pay/sponsor to get this fixed

**Comment by sberkeo** [comment]
I tried beta 8 and the problem was completely solved, you are great. I will use the vision camera in a sweet project. I am eager to collaborate in the future. continue to improve

**Comment by mrousavy** [comment]
Awesome, great to hear - thanks!
