### ISSUE TITLE
🐛 [iOS] TypeError: Cannot read property 'CameraDevices' of undefined

### ISSUE THREAD

**Issue by short-dsb** [cuvent/react-native-vision-camera#3048]
### What's happening?

Trying to invoke `useCameraDevice` on an iOS simulator in 4.4.1 results in a JS exception:

> Error: Exception in HostObject::get: for prop 'CameraDevices': <unknown exception>, js engine: hermes
> TypeError: Cannot read property 'CameraDevices' of undefined

This issue was not present in 4.4.0.

### Reproduceable Code

```tsx
const device = useCameraDevice("back", {
  physicalDevices: [
    "ultra-wide-angle-camera",
    "wide-angle-camera",
    "telephoto-camera",
  ],
});

<Camera
  ref={camera}
  device={device}
  enableZoomGesture={true}
  isActive={isActive}
  photo={true}
  resizeMode="contain"
  style={styles.camera}
/>
```

### Relevant log output

```shell
13:06:01.742: [error] 📸 VisionCamera.physicalDeviceDescriptor: Unknown AVCaptureDevice.DeviceType ()! Falling back to wide-angle-camera..
```

### Camera Device

```json
// N/A the exception prevents this from being logged.
```

### Device

iPhone 15 simulator (iOS 17.2)

### VisionCamera Version

4.4.1

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by rubbishCoder** [comment]
@short-dsb  try downgrading to the below version, it worked for me

"react-native-vision-camera": "4.4.0"

**Comment by fleuverouge** [comment]
> @short-dsb try downgrading to the below version, it worked for me
> 
> "react-native-vision-camera": "4.4.0"

Version 4.4.0 has issues with orientations in older iOS so it's not an option.

**Comment by Dat-Mobile** [comment]
I'm using this as the workaround, wait for the crash to fix in the next version
```
import DeviceInfo from 'react-native-device-info'

const device = DeviceInfo.isEmulator() ? null : useCameraDevice("back");
```

**Comment by short-dsb** [comment]
Unfortunately, that’s not a valid workaround as React hooks cannot be called conditionally.

**Comment by DarkShtir** [comment]
Template solutions
```typescript
// FIXME: For simulators, remove after upgrade to new version of `react-native-vision-camera`
const useGetCameraDevice = DeviceInfo.isEmulatorSync() ? () => undefined : useCameraDevice;

const MyCameraComponent:FC = ()=>{
  const device = useGetCameraDevice("back")
}
```

**Comment by short-dsb** [comment]
:nauseated_face:

**Comment by znikap** [comment]
Same issue, but I haven't found the solution yet, so we've downgraded the version to 3.9.2 😪

**Comment by Technaur** [comment]
As a temporary workaround for version 4.4.1, I created this patch. Should only happen on devices with no camera's, like the iOS simulator.

In `node_modules/react-native-vision-camera/src/hooks/useCameraDevices.ts`, modify this line 

`const [devices, setDevices] = useState(() => CameraDevices.getAvailableCameraDevices())` 
to be 
`const [devices, setDevices] = useState(() => CameraDevices ? CameraDevices.getAvailableCameraDevices() : {} as CameraDevice[])`

Here is the complete patch file content below.

`patches/react-native-vision-camera+4.4.1.patch`

```
diff --git a/node_modules/react-native-vision-camera/src/hooks/useCameraDevices.ts b/node_modules/react-native-vision-camera/src/hooks/useCameraDevices.ts
index 6dbd038..a489286 100644
--- a/node_modules/react-native-vision-camera/src/hooks/useCameraDevices.ts
+++ b/node_modules/react-native-vision-camera/src/hooks/useCameraDevices.ts
@@ -10,7 +10,7 @@ import { CameraDevices } from '../CameraDevices'
  * so the result of this function might update over time.
  */
 export function useCameraDevices(): CameraDevice[] {
-  const [devices, setDevices] = useState(() => CameraDevices.getAvailableCameraDevices())
+  const [devices, setDevices] = useState(() => CameraDevices ? CameraDevices.getAvailableCameraDevices() : {} as CameraDevice[])
 
   useEffect(() => {
     const listener = CameraDevices.addCameraDevicesChangedListener((newDevices) => {

```

**Comment by Technaur** [comment]
I reverted to version 4.3.2 from 4.4.1. `"react-native-vision-camera": "4.3.2",` (Be sure to remove the carot `^` in front of the version number)

I hope it helps

**Comment by hanseulhee** [comment]
I tried downgrading 4.3.2 but the same problem occurs.

`Exception in HostObject::get: for prop 'CameraDevices': <unknown exception>`

**Comment by mrousavy** [comment]
Fixed in https://github.com/mrousavy/react-native-vision-camera/pull/3064.

**Comment by mrousavy** [comment]
If you appreciate me dedicating time to fix issues and improve VisionCamera, please consider sponsoring me on GitHub :)

**Comment by fbele** [comment]
> Fixed in #3064.

I have updated the library to current version v4.5.0 but I am still getting this error with iOS simulator. Is it supposed to be fixed already?

**Comment by Diegoh-dev** [comment]
I'm using version "^4.5.3", but it still gives the same error. Android Emulator

**Comment by bitsmanent** [comment]
I end up managing the issues like this:

```
const HAS_CAMERA_DEVICES = Camera.getAvailableCameraDevices().length > 0;
```

Then I can toggle recording buttons or `Camera` view according.

Hope this helps.

**Comment by gvNN7** [comment]
Still getting this error on emulators.

Context:

react-native: 0.76.9
package version: 4.7.3

Any advices?

**Comment by navyag-glitch** [comment]
Still getting this error on emulators.
react-native: 0.78.2
package version: 3.9.2

error1:
App.js:9 TypeError: Cannot read property 'getConstants' of null, js engine: hermes Error Component Stack:
   error2:
 TypeError: Cannot read property 'CameraDevices' of undefined

any solutions help me!!!
