### ISSUE TITLE
🐛 Fails to build on react-native 0.76 on Android

### ISSUE THREAD

**Issue by hsjoberg** [cuvent/react-native-vision-camera#3260]
### What's happening?

Hi, when building using react-native 0.76, react-native-vision-camera fails with the following error:

```
C/C++: VisionCamera: Frame Processors: OFF!
C/C++: CMake Error at CMakeLists.txt:26 (add_library):
C/C++:   Target "VisionCamera" links to target "ReactAndroid::reactnativejni" but
C/C++:   the target was not found.  Perhaps a find_package() call is missing for an
C/C++:   IMPORTED target, or an ALIAS target is missing?
```

Both on new and old arch.

### Reproduceable Code

```tsx
N/A.

Check my repro here: https://github.com/hsjoberg/rn76-vision-camera-bug

It's simply a react-community cli project with react-native-vision-camera@4.5.3 added.
```

### Relevant log output

```shell
See above.
```

### Camera Device

```json
.
```

### Device

Emulator

### VisionCamera Version

4.5.3

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by OnurGuersoy** [comment]
Same issue here

**Comment by benoitvallon** [comment]
Here is the error I am seeing, I hope this can help

```
Caused by: com.android.ide.common.process.ProcessException:
Error while executing process /YYY/Library/Android/sdk/cmake/3.22.1/bin/cmake with arguments
{
    -H/XXX/node_modules/react-native-vision-camera/android
    -DCMAKE_SYSTEM_NAME=Android
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    -DCMAKE_SYSTEM_VERSION=24
    -DANDROID_PLATFORM=android-24
    -DANDROID_ABI=arm64-v8a
    -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a
    -DANDROID_NDK=/YYY/Library/Android/sdk/ndk/26.1.10909125
    -DCMAKE_ANDROID_NDK=/YYY/Library/Android/sdk/ndk/26.1.10909125
    -DCMAKE_TOOLCHAIN_FILE=/YYY/Library/Android/sdk/ndk/26.1.10909125/build/cmake/android.toolchain.cmake
    -DCMAKE_MAKE_PROGRAM=/YYY/Library/Android/sdk/cmake/3.22.1/bin/ninja
    -DCMAKE_CXX_FLAGS=-O2
    -frtti
    -fexceptions
    -Wall
    -Wno-unused-variable
    -fstack-protector-all
    -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/XXX/node_modules/react-native-vision-camera/android/build/intermediates/cxx/RelWithDebInfo/6f6a114v/obj/arm64-v8a
    -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/XXX/node_modules/react-native-vision-camera/android/build/intermediates/cxx/RelWithDebInfo/6f6a114v/obj/arm64-v8a
    -DCMAKE_BUILD_TYPE=RelWithDebInfo
    -DCMAKE_FIND_ROOT_PATH=/XXX/node_modules/react-native-vision-camera/android/.cxx/RelWithDebInfo/6f6a114v/prefab/arm64-v8a/prefab
    -B/XXX/node_modules/react-native-vision-camera/android/.cxx/RelWithDebInfo/6f6a114v/arm64-v8a
    -GNinja
    -DANDROID_STL=c++_shared
    -DNODE_MODULES_DIR=/XXX/node_modules
    -DENABLE_FRAME_PROCESSORS=OFF
}
```

**Comment by Gautham495** [comment]
Yes. This is happening and the react native worklets core also fails to build in android but works well in ios new arch.

**Comment by dlalas** [comment]
Same issue here!

**Comment by tux2nicolae** [comment]
+1

**Comment by RicardoGuiliani** [comment]
Same issue here, after upgrading from react-native 0.75.4 to 0.76

**Comment by AdrianCD101** [comment]
+1

**Comment by HungGiaPham** [comment]
Same issue here, after upgrading from react-native 0.75.4 to 0.76

**Comment by leidaibo-lab** [comment]
Same issue here, after upgrading from react-native 0.75.4 to 0.76
 
Relatively urgent, I decided to promote the upgrade of RN0.76 version

**Comment by zhang-brook** [comment]
Same issue here, after upgrading from react-native 0.75.4 to 0.76
using react-native-vision-camera@4.5.3

```bash
> Task :react-native-vision-camera:configureCMakeDebug[arm64-v8a] FAILED
C/C++: VisionCamera: Frame Processors: OFF!
C/C++: CMake Error at CMakeLists.txt:26 (add_library):
C/C++:   Target "VisionCamera" links to target "ReactAndroid::reactnativejni" but
C/C++:   the target was not found.  Perhaps a find_package() call is missing for an
C/C++:   IMPORTED target, or an ALIAS target is missing?
C/C++: CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by nazacity** [comment]
Same issue here, after upgrading from react-native 0.75.4 to 0.76

**Comment by kexi** [comment]
+1

**Comment by corbella83** [comment]
Same here. Temporarily, I managed to get it working by changing these lines in the CMakeLists.txt of the library:

1) Replace the `ReactAndroid::reactnativejni` to `ReactAndroid::reactnative`

2) Replace the 3 `${NODE_MODULES_DIR}/react-native` by `${REACT_NATIVE_DIR}`

Edit: There is a last step to make it work:

3) Add `"**/libreactnative.so",` to the _exclude_ array at build.gradle of the library

**Comment by Gautham495** [comment]
@corbella83 - do you use worklets-core? If yes - please provide a fix if you have one.

**Comment by laurensk** [comment]
+1

**Comment by Romick2005** [comment]
```
Task :react-native-vision-camera:configureCMakeDebug[arm64-v8a] FAILED

[CXX1429] error when building with cmake using /Users/user/repo/app/na-mobile/node_modules/react-native-vision-camera/android/CMakeLists.txt: -- The C compiler identification is Clang 17.0.2

C++ build system [configure] failed while executing:
  VisionCamera: Frame Processors: OFF!
  CMake Error at CMakeLists.txt:26 (add_library):
    Target "VisionCamera" links to target "ReactAndroid::reactnativejni" but
    the target was not found.  Perhaps a find_package() call is missing for an
    IMPORTED target, or an ALIAS target is missing?
 
  CMake Generate step failed.  Build files cannot be regenerated correctly. : com.android.ide.common.process.ProcessException: -- The C compiler identification is Clang 17.0.2
```

**Comment by TorrCod** [comment]
+1

**Comment by Mhp23** [comment]
To solve the problem go to `YOUR_PROJECT/node_modules/react-native-vision-camera/android/CMakeLists` then replace the following line:

`ReactAndroid::reactnativejni`

By

`ReactAndroid::reactnative`

The build issue will be solved. If you'd like to patch until the next update is available, use [patch package](https://github.com/ds300/patch-package)

**Comment by Gautham495** [comment]
@Mhp23 - I can confirm this works and builds.

Thanks!

**Comment by AjayFrancisTechversant** [comment]
@Mhp23 Its not working for me.

**Comment by ajay-ranga** [comment]
https://github.com/mrousavy/react-native-vision-camera/issues/3260#issuecomment-2438632177

Thanks a lot man.
It worked.
Anyone still getting same issue can use this patch file.
[react-native-vision-camera+4.5.3.patch](https://github.com/user-attachments/files/17557123/react-native-vision-camera%2B4.5.3.patch)

**Comment by mateusschenato** [comment]
> [#3260 (comment)](https://github.com/mrousavy/react-native-vision-camera/issues/3260#issuecomment-2438632177)
> 
> Thanks a lot man. It worked. Anyone still getting same issue can use this patch file. [react-native-vision-camera+4.5.3.patch](https://github.com/user-attachments/files/17557123/react-native-vision-camera%2B4.5.3.patch)

Thanks !

I also added something on here and now it's working.

`react-native-vision-camera+4.5.3.patch`
```diff --git a/node_modules/react-native-vision-camera/android/CMakeLists.txt b/node_modules/react-native-vision-camera/android/CMakeLists.txt
index 1460dbd..3d4e2ae 100644
--- a/node_modules/react-native-vision-camera/android/CMakeLists.txt
+++ b/node_modules/react-native-vision-camera/android/CMakeLists.txt
@@ -49,9 +49,9 @@ target_include_directories(
         "src/main/cpp"
         "src/main/cpp/frameprocessors"
         "src/main/cpp/frameprocessors/java-bindings"
-        "${NODE_MODULES_DIR}/react-native/ReactCommon"
-        "${NODE_MODULES_DIR}/react-native/ReactCommon/callinvoker"
-        "${NODE_MODULES_DIR}/react-native/ReactAndroid/src/main/jni/react/turbomodule" # <-- CallInvokerHolder JNI wrapper
+        "${REACT_NATIVE_DIR}/ReactCommon"
+        "${REACT_NATIVE_DIR}/ReactCommon/callinvoker"
+        "${REACT_NATIVE_DIR}/ReactAndroid/src/main/jni/react/turbomodule" # <-- CallInvokerHolder JNI wrapper
 )
 
 # Link everything together
@@ -60,7 +60,7 @@ target_link_libraries(
         ${LOG_LIB}                          # <-- Logcat logger
         android                             # <-- Android JNI core
         ReactAndroid::jsi                   # <-- RN: JSI
-        ReactAndroid::reactnativejni        # <-- RN: React Native JNI bindings
+        ReactAndroid::reactnative        # <-- RN: React Native JNI bindings
         fbjni::fbjni                        # <-- fbjni
 )
 ```

**Comment by corbella83** [comment]
This is not yet solved. Might seem solved because of caches. But if you do a clean build will have this error:

`2 files found with path 'lib/arm64-v8a/libreactnative.so' from inputs`

To solve it, add this line to YOUR_PROJECT/node_modules/react-native-vision-camera/android/build.gradle [packagingOptions - excludes]

`"**/libreactnative.so",`

**Comment by TorrCod** [comment]
@corbella83 same.. the i got the exact same error

**Comment by Driveemode** [comment]
> [packagingOptions - excludes]

in which line?

**Comment by corbella83** [comment]
> > [packagingOptions - excludes]
> 
> in which line?

It has already been merged this change: https://github.com/mrousavy/react-native-vision-camera/pull/3281/files

FYI: Approximately on line 170. Anywhere in the 'exludes' array

```
  packagingOptions {
    doNotStrip resolveBuildType() == "debug" ? "**/**/*.so" : ""
    excludes = [
            "META-INF",
            "META-INF/**",
            "**/libc++_shared.so",
            "**/libfbjni.so",
            "**/libjsi.so",
            "**/libfolly_json.so",
            "**/libfolly_runtime.so",
            "**/libglog.so",
            "**/libhermes.so",
            "**/libhermes-executor-debug.so",
            "**/libhermes_executor.so",
            "**/libreactnative.so",
            "**/libturbomodulejsijni.so",
            "**/libreact_nativemodule_core.so",
            "**/libjscexecutor.so"
    ]
  }
```

**Comment by TorrCod** [comment]
@corbella83  @Driveemode  this was fixed in [4.6.1](https://github.com/mrousavy/react-native-vision-camera/pull/3281)

**Comment by jobaerhassan** [comment]
Just deleting the .gradle folder works for me..no need any patch.
device: mac m2 pro
RN version: 0.71
vision-camera version: 4.0.0

**Comment by KDLPro** [comment]
I still have this issueSame thing happens in my build. I used React-Native 0.74.5 with `npx expo run:android`

```
> Task :react-native-vision-camera:configureCMakeDebug[armeabi-v7a] FAILED
C/C++: VisionCamera: Frame Processors: ON!
C/C++: VisionCamera: Linking react-native-worklets...
C/C++: CMake Error at CMakeLists.txt:26 (add_library):
C/C++:   Target "VisionCamera" links to target "ReactAndroid::reactnative" but the
C/C++:   target was not found.  Perhaps a find_package() call is missing for an
C/C++:   IMPORTED target, or an ALIAS target is missing?
C/C++: CMake Generate step failed.  Build files cannot be regenerated correctly.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-vision-camera:configureCMakeDebug[armeabi-v7a]'.
> [CXX1429] error when building with cmake using D:\Mobile-Dashboard\node_modules\react-native-vision-camera\android\CMakeLists.txt: -- Configuring done
  -- Generating done

  C++ build system [configure] failed while executing:
      @echo off
      "C:\\Users\\kenne\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\cmake.exe" ^
        "-HD:\\Mobile-Dashboard\\node_modules\\react-native-vision-camera\\android" ^
        "-DCMAKE_SYSTEM_NAME=Android" ^
        "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" ^
        "-DCMAKE_SYSTEM_VERSION=23" ^
        "-DANDROID_PLATFORM=android-23" ^
        "-DANDROID_ABI=armeabi-v7a" ^
        "-DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a" ^
        "-DANDROID_NDK=C:\\Users\\kenne\\AppData\\Local\\Android\\Sdk\\ndk\\26.1.10909125" ^
        "-DCMAKE_ANDROID_NDK=C:\\Users\\kenne\\AppData\\Local\\Android\\Sdk\\ndk\\26.1.10909125" ^
        "-DCMAKE_TOOLCHAIN_FILE=C:\\Users\\kenne\\AppData\\Local\\Android\\Sdk\\ndk\\26.1.10909125\\build\\cmake\\android.toolchain.cmake" ^
        "-DCMAKE_MAKE_PROGRAM=C:\\Users\\kenne\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
        "-DCMAKE_CXX_FLAGS=-O2 -frtti -fexceptions -Wall -Wno-unused-variable -fstack-protector-all" ^
        "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\\Mobile-Dashboard\\node_modules\\react-native-vision-camera\\android\\build\\intermediates\\cxx\\Debug\\4p3d4f4p\\obj\\armeabi-v7a" ^     
        "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=D:\\Mobile-Dashboard\\node_modules\\react-native-vision-camera\\android\\build\\intermediates\\cxx\\Debug\\4p3d4f4p\\obj\\armeabi-v7a" ^     
        "-DCMAKE_BUILD_TYPE=Debug" ^
        "-DCMAKE_FIND_ROOT_PATH=D:\\Mobile-Dashboard\\node_modules\\react-native-vision-camera\\android\\.cxx\\Debug\\4p3d4f4p\\prefab\\armeabi-v7a\\prefab" ^
        "-BD:\\Mobile-Dashboard\\node_modules\\react-native-vision-camera\\android\\.cxx\\Debug\\4p3d4f4p\\armeabi-v7a" ^
        -GNinja ^
        "-DANDROID_STL=c++_shared" ^
        "-DNODE_MODULES_DIR=D:\\Mobile-Dashboard\\node_modules" ^
        "-DENABLE_FRAME_PROCESSORS=ON"
    from D:\Mobile-Dashboard\node_modules\react-native-vision-camera\android
  VisionCamera: Frame Processors: ON!
  VisionCamera: Linking react-native-worklets...
  CMake Error at CMakeLists.txt:26 (add_library):
    Target "VisionCamera" links to target "ReactAndroid::reactnative" but the
    target was not found.  Perhaps a find_package() call is missing for an
    IMPORTED target, or an ALIAS target is missing?


  CMake Generate step failed.  Build files cannot be regenerated correctly. : com.android.ide.common.process.ProcessException: -- Configuring done
  -- Generating done

  C++ build system [configure] failed while executing:
      @echo off
      "C:\\Users\\kenne\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\cmake.exe" ^
        "-HD:\\Mobile-Dashboard\\node_modules\\react-native-vision-camera\\android" ^
        "-DCMAKE_SYSTEM_NAME=Android" ^
        "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" ^
        "-DCMAKE_SYSTEM_VERSION=23" ^
        "-DANDROID_PLATFORM=android-23" ^
        "-DANDROID_ABI=armeabi-v7a" ^
        "-DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a" ^
        "-DANDROID_NDK=C:\\Users\\kenne\\AppData\\Local\\Android\\Sdk\\ndk\\26.1.10909125" ^
        "-DCMAKE_ANDROID_NDK=C:\\Users\\kenne\\AppData\\Local\\Android\\Sdk\\ndk\\26.1.10909125" ^
        "-DCMAKE_TOOLCHAIN_FILE=C:\\Users\\kenne\\AppData\\Local\\Android\\Sdk\\ndk\\26.1.10909125\\build\\cmake\\android.toolchain.cmake" ^
        "-DCMAKE_MAKE_PROGRAM=C:\\Users\\kenne\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
        "-DCMAKE_CXX_FLAGS=-O2 -frtti -fexceptions -Wall -Wno-unused-variable -fstack-protector-all" ^
        "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\\Mobile-Dashboard\\node_modules\\react-native-vision-camera\\android\\build\\intermediates\\cxx\\Debug\\4p3d4f4p\\obj\\armeabi-v7a" ^     
        "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=D:\\Mobile-Dashboard\\node_modules\\react-native-vision-camera\\android\\build\\intermediates\\cxx\\Debug\\4p3d4f4p\\obj\\armeabi-v7a" ^     
        "-DCMAKE_BUILD_TYPE=Debug" ^
        "-DCMAKE_FIND_ROOT_PATH=D:\\Mobile-Dashboard\\node_modules\\react-native-vision-camera\\android\\.cxx\\Debug\\4p3d4f4p\\prefab\\armeabi-v7a\\prefab" ^
        "-BD:\\Mobile-Dashboard\\node_modules\\react-native-vision-camera\\android\\.cxx\\Debug\\4p3d4f4p\\armeabi-v7a" ^
        -GNinja ^
        "-DANDROID_STL=c++_shared" ^
        "-DNODE_MODULES_DIR=D:\\Mobile-Dashboard\\node_modules" ^
        "-DENABLE_FRAME_PROCESSORS=ON"
    from D:\Mobile-Dashboard\node_modules\react-native-vision-camera\android
  VisionCamera: Frame Processors: ON!
  VisionCamera: Linking react-native-worklets...
  CMake Error at CMakeLists.txt:26 (add_library):
    Target "VisionCamera" links to target "ReactAndroid::reactnative" but the
    target was not found.  Perhaps a find_package() call is missing for an
    IMPORTED target, or an ALIAS target is missing?


  CMake Generate step failed.  Build files cannot be regenerated correctly.
        at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt.execute(ExecuteProcess.kt:288)
        at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt$executeProcess$1.invoke(ExecuteProcess.kt:108)
        at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt$executeProcess$1.invoke(ExecuteProcess.kt:106)
        at com.android.build.gradle.internal.cxx.timing.TimingEnvironmentKt.time(TimingEnvironment.kt:32)
        at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt.executeProcess(ExecuteProcess.kt:106)
        at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt.executeProcess$default(ExecuteProcess.kt:85)
        at com.android.build.gradle.tasks.CmakeQueryMetadataGenerator.executeProcess(CmakeFileApiMetadataGenerator.kt:59)
        at com.android.build.gradle.tasks.ExternalNativeJsonGenerator$configureOneAbi$1$1$3.invoke(ExternalNativeJsonGenerator.kt:246)
        at com.android.build.gradle.tasks.ExternalNativeJsonGenerator$configureOneAbi$1$1$3.invoke(ExternalNativeJsonGenerator.kt:246)
        at com.android.build.gradle.internal.cxx.timing.TimingEnvironmentKt.time(TimingEnvironment.kt:32)
        at com.android.build.gradle.tasks.ExternalNativeJsonGenerator.configureOneAbi(ExternalNativeJsonGenerator.kt:246)
        at com.android.build.gradle.tasks.ExternalNativeJsonGenerator.configure(ExternalNativeJsonGenerator.kt:112)
        at com.android.build.gradle.tasks.ExternalNativeBuildJsonTask.doTaskAction(ExternalNativeBuildJsonTask.kt:90)
        at com.android.build.gradle.internal.tasks.UnsafeOutputsTask$taskAction$$inlined$recordTaskAction$1.invoke(BaseTask.kt:65)
        at com.android.build.gradle.internal.tasks.Blocks.recordSpan(Blocks.java:51)
        at com.android.build.gradle.internal.tasks.UnsafeOutputsTask.taskAction(UnsafeOutputsTask.kt:63)
        at jdk.internal.reflect.GeneratedMethodAccessor1660.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
        at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:244)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:229)
        at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:212)
        at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:195)
        at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:162)
        at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:105)
        at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:44)
        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:59)
        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:56)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:56)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:44)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:41)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:74)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)
        at org.gradle.internal.execution.steps.PreCreateOutputParentsStep.execute(PreCreateOutputParentsStep.java:50)
        at org.gradle.internal.execution.steps.PreCreateOutputParentsStep.execute(PreCreateOutputParentsStep.java:28)
        at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:67)
        at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:37)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:61)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:26)
        at org.gradle.internal.execution.steps.CaptureOutputsAfterExecutionStep.execute(CaptureOutputsAfterExecutionStep.java:67)
        at org.gradle.internal.execution.steps.CaptureOutputsAfterExecutionStep.execute(CaptureOutputsAfterExecutionStep.java:45)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:40)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:29)
        at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:189)
        at org.gradle.internal.execution.steps.BuildCacheStep.lambda$execute$1(BuildCacheStep.java:75)
        at org.gradle.internal.Either$Right.fold(Either.java:175)
        at org.gradle.internal.execution.caching.CachingState.fold(CachingState.java:62)
        at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:73)
        at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:48)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:46)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:35)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:76)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$2(SkipUpToDateStep.java:54)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
        at org.gradle.internal.execution.steps.ResolveIncrementalCachingStateStep.executeDelegate(ResolveIncrementalCachingStateStep.java:49)
        at org.gradle.internal.execution.steps.ResolveIncrementalCachingStateStep.executeDelegate(ResolveIncrementalCachingStateStep.java:27)
        at org.gradle.internal.execution.steps.AbstractResolveCachingStateStep.execute(AbstractResolveCachingStateStep.java:71)
        at org.gradle.internal.execution.steps.AbstractResolveCachingStateStep.execute(AbstractResolveCachingStateStep.java:39)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:65)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:36)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:106)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:55)
        at org.gradle.internal.execution.steps.AbstractCaptureStateBeforeExecutionStep.execute(AbstractCaptureStateBeforeExecutionStep.java:64)
        at org.gradle.internal.execution.steps.AbstractCaptureStateBeforeExecutionStep.execute(AbstractCaptureStateBeforeExecutionStep.java:43)
        at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.executeWithNonEmptySources(AbstractSkipEmptyWorkStep.java:125)
        at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.execute(AbstractSkipEmptyWorkStep.java:56)
        at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.execute(AbstractSkipEmptyWorkStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
        at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:36)
        at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:23)
        at org.gradle.internal.execution.steps.HandleStaleOutputsStep.execute(HandleStaleOutputsStep.java:75)
        at org.gradle.internal.execution.steps.HandleStaleOutputsStep.execute(HandleStaleOutputsStep.java:41)
        at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.lambda$execute$0(AssignMutableWorkspaceStep.java:35)
        at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:289)
        at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.execute(AssignMutableWorkspaceStep.java:31)
        at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.execute(AssignMutableWorkspaceStep.java:22)
        at org.gradle.internal.execution.steps.ChoosePipelineStep.execute(ChoosePipelineStep.java:40)
        at org.gradle.internal.execution.steps.ChoosePipelineStep.execute(ChoosePipelineStep.java:23)
        at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.lambda$execute$2(ExecuteWorkBuildOperationFiringStep.java:67)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:67)
        at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:39)
        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:46)
        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:34)
        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:48)
        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:35)
        at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:61)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:127)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:116)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:331)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:318)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.lambda$execute$0(DefaultTaskExecutionGraph.java:314)
        at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:314)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
        at org.gradle.execution.plan.DefaultPlanExecutor.process(DefaultPlanExecutor.java:116)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.executeWithServices(DefaultTaskExecutionGraph.java:138)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.execute(DefaultTaskExecutionGraph.java:123)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:35)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:51)
        at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor$ExecuteTasks.call(BuildOperationFiringBuildWorkerExecutor.java:54)
        at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor$ExecuteTasks.call(BuildOperationFiringBuildWorkerExecutor.java:43)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor.execute(BuildOperationFiringBuildWorkerExecutor.java:40)
        at org.gradle.internal.build.DefaultBuildLifecycleController.lambda$executeTasks$10(DefaultBuildLifecycleController.java:313)
        at org.gradle.internal.model.StateTransitionController.doTransition(StateTransitionController.java:266)
        at org.gradle.internal.model.StateTransitionController.lambda$tryTransition$8(StateTransitionController.java:177)
        at org.gradle.internal.work.DefaultSynchronizer.withLock(DefaultSynchronizer.java:44)
        at org.gradle.internal.model.StateTransitionController.tryTransition(StateTransitionController.java:177)
        at org.gradle.internal.build.DefaultBuildLifecycleController.executeTasks(DefaultBuildLifecycleController.java:304)
        at org.gradle.internal.build.DefaultBuildWorkGraphController$DefaultBuildWorkGraph.runWork(DefaultBuildWorkGraphController.java:220)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:264)
        at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:128)
        at org.gradle.composite.internal.DefaultBuildController.doRun(DefaultBuildController.java:181)
        at org.gradle.composite.internal.DefaultBuildController.access$000(DefaultBuildController.java:50)
        at org.gradle.composite.internal.DefaultBuildController$BuildOpRunnable.lambda$run$0(DefaultBuildController.java:198)
        at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
        at org.gradle.composite.internal.DefaultBuildController$BuildOpRunnable.run(DefaultBuildController.java:198)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:842)
  Caused by: com.android.ide.common.process.ProcessException: Error while executing process C:\Users\kenne\AppData\Local\Android\Sdk\cmake\3.22.1\bin\cmake.exe with arguments {-HD:\Mobile-Dashboard\node_modules\react-native-vision-camera\android -DCMAKE_SYSTEM_NAME=Android -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SYSTEM_VERSION=23 -DANDROID_PLATFORM=android-23 -DANDROID_ABI=armeabi-v7a -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a -DANDROID_NDK=C:\Users\kenne\AppData\Local\Android\Sdk\ndk\26.1.10909125 -DCMAKE_ANDROID_NDK=C:\Users\kenne\AppData\Local\Android\Sdk\ndk\26.1.10909125 -DCMAKE_TOOLCHAIN_FILE=C:\Users\kenne\AppData\Local\Android\Sdk\ndk\26.1.10909125\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=C:\Users\kenne\AppData\Local\Android\Sdk\cmake\3.22.1\bin\ninja.exe -DCMAKE_CXX_FLAGS=-O2 -frtti -fexceptions -Wall -Wno-unused-variable -fstack-protector-all -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\Mobile-Dashboard\node_modules\react-native-vision-camera\android\build\intermediates\cxx\Debug\4p3d4f4p\obj\armeabi-v7a -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=D:\Mobile-Dashboard\node_modules\react-native-vision-camera\android\build\intermediates\cxx\Debug\4p3d4f4p\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DCMAKE_FIND_ROOT_PATH=D:\Mobile-Dashboard\node_modules\react-native-vision-camera\android\.cxx\Debug\4p3d4f4p\prefab\armeabi-v7a\prefab -BD:\Mobile-Dashboard\node_modules\react-native-vision-camera\android\.cxx\Debug\4p3d4f4p\armeabi-v7a -GNinja -DANDROID_STL=c++_shared -DNODE_MODULES_DIR=D:\Mobile-Dashboard\node_modules -DENABLE_FRAME_PROCESSORS=ON}
        at com.android.build.gradle.internal.process.GradleProcessResult.buildProcessException(GradleProcessResult.java:73)
        at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:48)
        at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt.execute(ExecuteProcess.kt:277)
        ... 171 more
  Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\kenne\AppData\Local\Android\Sdk\cmake\3.22.1\bin\cmake.exe'' finished with non-zero exit value 1    
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:442)
        at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:46)
        ... 172 more```

**Comment by vladvlasov256** [comment]
As a workaround, turn off the [frame processor](https://react-native-vision-camera.com/docs/guides/frame-processors) if your app doesn't use one.
Then apply @corbella83's patch.
