### ISSUE TITLE
🐛 Google Compliance Warning: 16KB Page Size Requirement (Android 15+) with react-native-vision-camera 4.6.4

### ISSUE THREAD

**Issue by sindhusingh** [cuvent/react-native-vision-camera#3630]
### What's happening?

We’ve recently started receiving compliance warnings from Google Play regarding the 16KB page size requirement (Android 15+), which specifically points to Vision Camera. We’re currently using react-native-vision-camera version 4.6.4. I wanted to check if there’s a specific version available that addresses this issue, or if it’s still under investigation, and if there’s any recommended way to resolve it?

<img width="1280" height="262" alt="Image" src="https://github.com/user-attachments/assets/d1d76b96-ad27-4254-88ea-0742ffbdbb75" />

### Reproduceable Code

```tsx
Google Compliance Warning, So no code added
```

### Relevant log output

```shell
Google Compliance Warning, So no code added
```

### Camera Device

```json
Google Compliance Warning, So no code added
```

### Device

Android

### VisionCamera Version

4.6.4

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [x] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [x] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [x] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by jslok** [comment]
4.7.0 added 16kb page support

**Comment by sindhusingh** [comment]
> 4.7.0 added 16kb page support

Okay @jslok , so if we bump the version from 4.6.4 to 4.7.2, that should resolve it, right?

**Comment by jslok** [comment]
> > 4.7.0 added 16kb page support
> 
> Okay [@jslok](https://github.com/jslok) , so if we bump the version from 4.6.4 to 4.7.2, that should resolve it, right?

Try it and let us know :)

**Comment by alikemalozgumus** [comment]
upgrade to 4.7.2 but its still showing not supported 16kb
 "react-native-vision-camera": "^4.7.2",

mmPsTqUeUG/lib/arm64-v8a/libVisionCamera.so: \e[31mUNALIGNED\e[0m (2**12)

**Comment by rezagaruda** [comment]
> upgrade to 4.7.2 but its still showing not supported 16kb "react-native-vision-camera": "^4.7.2",
> 
> mmPsTqUeUG/lib/arm64-v8a/libVisionCamera.so: \e[31mUNALIGNED\e[0m (2**12)

I also get the same issue

**Comment by jslok** [comment]
It works for me. Make sure you clean all cache and .gradle folders

**Comment by rezagaruda** [comment]
> It works for me. Make sure you clean all cache and .gradle folders 

Which ndk version are you using?

**Comment by alikemalozgumus** [comment]
> > It works for me. Make sure you clean all cache and .gradle folders
> 
> Which ndk version are you using?

ndkVersion = "26.1.10909125"

**Comment by jslok** [comment]
> > > It works for me. Make sure you clean all cache and .gradle folders
> > 
> > Which ndk version are you using?
> 
> ndkVersion = "26.1.10909125"

Pretty sure you need rn >=0.77 and ndk 27.

**Comment by MariaFF** [comment]
Let me also share here what worked for me:

"react-native": "0.79.3",
"react-native-worklets-core": "^1.3.3", <-- ADD
"react-native-vision-camera": "4.7.1",

android/build.gradle
ndkVersion = "27.1.12297006"

**Comment by michalis-ligopsychakis** [comment]
@MariaFF NDK version 27 doesn't support 16KB page size for android..
so we cannot downgrade the NDK version..

**Comment by alikemalozgumus** [comment]
thanks it works for me 
 ndkVersion = "27.1.12297006"
"react-native-vision-camera": "^4.7.2",
"react": "19.0.0",
    "react-native": "0.79.2",

**Comment by Acex187x** [comment]
NDK 28+ crashes apps right on startup, while 27 works fine with the flag for flexible page size.

**Comment by Jigisha820** [comment]
Thank you, It worked for me on Emulators. Has anyone tried on a Physical device which have a 16 KB page size?
ndkVersion = "27.1.12297006"
"react-native-vision-camera": "^4.7.2",
"react": "19.0.0",
"react-native": "0.79.2",

**Comment by Acex187x** [comment]
@Jigisha820 It seems they don't exist yet 😅. That's why they're making us update the apps.

**Comment by jslok** [comment]
> It works for me. Make sure you clean all cache and .gradle folders

**Comment by Jigisha820** [comment]
> [@Jigisha820](https://github.com/Jigisha820) It seems they don't exist yet 😅. That's why they're making us update the apps.

@Acex187x True, however, this option is available on Pixel 8 and Pixel 8 Pro starting in the Android 15 QPR1 Beta. We can switch from the default size to 16KB

**Comment by MuazzezA** [comment]
I'm getting the following error when starting my Android app after upgrading the NDK version. This crash occurs immediately when the app starts.

**Failed to load VisionCamera C++ library!
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__cxa_init_primary_exception" referenced by "/data/app/~ **somepath** /base.apk!/lib/arm64-v8a/libVisionCamera.so"**


 ```
  minSdkVersion = 27
  compileSdkVersion = 35
  targetSdkVersion = 35
  ndkVersion = "28.2.13676358"
  kotlinVersion = "1.9.25"
```

```
 "react": "18.3.1",
 "react-native": "0.76.9",
 "react-native-vision-camera": "4.7.1",
```

The issue did not occur with the previous setup (NDK 26.1.10909125 and react-native-vision-camera ^4.3.1).

Also, I added the following code when I was on ndk v28 but it did not work.

```
set_target_properties(${PACKAGE_NAME} PROPERTIES
    LINK_FLAGS "-Wl,-z,max-page-size=16384"
)
```
and didn't work >  rezagaruda:fix/android-16kb-page-size-support

**Comment by PWAronofsky** [comment]
I am also getting this error in our project where we need ndk 28. Is there a workaround for this?
```
Error: Failed to load VisionCamera C++ library!
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__cxa_init_primary_exception" referenced by "/data/app/~ourpath/base.apk!/lib/arm64-v8a/libVisionCamera.so"...
	at java.lang.Runtime.loadLibrary0(Runtime.java:1090)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
	at java.lang.System.loadLibrary(System.java:1765)
	at com.mrousavy.camera.react.CameraViewModule.<clinit>(CameraViewModule.kt:48)
	at com.mrousavy.camera.react.CameraPackage.createNativeModules(CameraPackage.kt:11)
	at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.kt:32)
	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.kt:39)
	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1576)
	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1547)
	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1458)
	at com.facebook.react.ReactInstanceManager.lambda$runCreateReactContextOnNewThread$2(ReactInstanceManager.java:1226)
	at com.facebook.react.ReactInstanceManager.$r8$lambda$PrBhihCbbAFk4ZReAALGanVLCyc(Unknown Source:0)
	at com.facebook.react.ReactInstanceManager$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1119)
FATAL EXCEPTION: create_react_context
Process: com.our.app, PID: 32176
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__cxa_init_primary_exception" referenced by "/data/app/~ourpath/base.apk!/lib/arm64-v8a/libVisionCamera.so"...
	at java.lang.Runtime.loadLibrary0(Runtime.java:1090)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
	at java.lang.System.loadLibrary(System.java:1765)
	at com.mrousavy.camera.react.CameraViewModule.<clinit>(CameraViewModule.kt:48)
	at com.mrousavy.camera.react.CameraPackage.createNativeModules(CameraPackage.kt:11)
	at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.kt:32)
	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.kt:39)
	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1576)
	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1547)
	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1458)
	at com.facebook.react.ReactInstanceManager.lambda$runCreateReactContextOnNewThread$2(ReactInstanceManager.java:1226)
	at com.facebook.react.ReactInstanceManager.$r8$lambda$PrBhihCbbAFk4ZReAALGanVLCyc(Unknown Source:0)
	at com.facebook.react.ReactInstanceManager$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1119)

```

```
    minSdkVersion = 28
    compileSdkVersion = 35
    targetSdkVersion = 35
    ndkVersion = "28.2.13676358"
```
```
    "react": "18.3.1",
    "react-native": "0.77.3",
    "react-native-vision-camera": "~4.7.3",
```

**Comment by mrousavy** [comment]
Are you 100% sure that you are building with NDK 28?

**Comment by PWAronofsky** [comment]
> Are you 100% sure that you are building with NDK 28?

Yes - also, this is regarding the crash that @MuazzezA mentioned. Should we open a new issue for it?

[EDIT]  [This comment ](https://github.com/mrousavy/react-native-vision-camera/issues/3548#issuecomment-3573539823) actually helped. It looks like React Native itself ships with `libc++_shared.so` built against ndk 27, and that causes conflicts. (The React Native upgrade tool still suggests 27, but we need to be on 28)

**Comment by rohan-h-7edge** [comment]
https://community.7edge.com/t/react-native-android-16-kb-page-size-fix-avoid-play-store-rejection/340

**Comment by mrousavy** [comment]
Hey! Sorry for the late reply and thank you for your issue report.
I was hyper-focused the entire winter to build the next major version of VisionCamera - and I think [VisionCamera V5](https://github.com/mrousavy/react-native-vision-camera/releases/tag/v5.0.0) fixes this! 🥳

Closing, but feel free to open a new issue if this still needs attention in V5! :)
